### ISSUE TITLE
Unable to import characters from client

### ISSUE THREAD

**Issue by mech422** [LotroCompanion/lotro-companion#618]
Hi!
  I don't seem to be able to import character data from the running client - from the character select screen OR from a logged in character.  I get the generic "Unable to get client data..." message but it does recognize I'm running the 64-bit client.  If it matters, I moved the the Documents/The Lord of the Rings Online to a new drive as I was getting tight on space (I made Documents/The Lord of the Rings Online a link to the new location and everything seems to be working properly).

Also do you happen to know of any documentation on how to retrieve information from the client, like LotroCompanion does?  I tried to find the relevant code in LotroCompanion but I couldn't find the file reads or API calls to do this ? Javas not my thing, but it looks like everything I found is a wrapper or interface?  I'd like to create a lil library for doing from Rust and Python so I can play with making my own stuff ... 

Thanks!

**Comment by dmorcellet** [comment]
Hi. This is a well known issue. On major Updates of the client, the value of "start" pointers change so the LC import breaks.
There is no written documentation on the import process. LC connects to the running client and reads its memory to gather character data. The code to do this is private, because it contains intimate knowledge of the client, that could be used to break the game.
Please join me on Discord (https://discord.gg/t2J4GDq) for further chat.

**Comment by dmorcellet** [comment]
Fixed with incoming release 23.0.41.0 (tomorrow).

**Comment by mech422** [comment]
Thanks! Looking forward to new release...

P.S. - I didn't realize windows let 1 process read another processes memory like that - as a unix guy, not sure if thats cool or scary :-)
